
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADELANTE ATRAS BEGIN COMA COMMENT DECIMALNUMBER DERECHA ELSE END ENDOFLINE ESPERAR EXTENSION FINPROGRAMA FRENAR FUNCION ID IF IGUAL INICIODEPROGRAMA IZQUIERDA LIBRERIA NUMBER OPERADOR OPERADORPUNTO PARENTESISA PARENTESISC PROCEDIMIENTO TYPE VARIABLE VARTYPESEPARATOR VPIN WHILEprograma : INICIODEPROGRAMA declaraciones FINPROGRAMAdeclaraciones : librerias\n                   | cuerpo librerias : LIBRERIA PARENTESISA ID OPERADORPUNTO EXTENSION PARENTESISC COMA librerias\n                | LIBRERIA PARENTESISA ID OPERADORPUNTO EXTENSION PARENTESISC ENDOFLINE cuerpo cuerpo : variable cuerpo\n            | funcion cuerpo\n            | asignacion cuerpo\n            | procedimiento cuerpo\n            | condicional cuerpo\n            | emptycondicional : IF PARENTESISA PARENTESISC BEGIN cuerpo END ENDOFLINE\n                 | IF PARENTESISA PARENTESISC BEGIN cuerpo END ELSE BEGIN cuerpo END ENDOFLINEprocedimiento : PROCEDIMIENTO ID PARENTESISA argumentos PARENTESISC ENDOFLINEasignacion : ID IGUAL ID ENDOFLINE\n                  | ID IGUAL NUMBER ENDOFLINE\n                  | ID IGUAL DECIMALNUMBER ENDOFLINE\n                  funcion : FUNCION ID PARENTESISA argumentos PARENTESISC VARTYPESEPARATOR TYPE ENDOFLINEvariable : VARIABLE PARENTESISA ID  VARTYPESEPARATOR TYPE PARENTESISC ENDOFLINE argumentos : ID VARTYPESEPARATOR TYPE COMA argumentos\n                 | ID VARTYPESEPARATOR TYPEempty :'
    
_lr_action_items = {'INICIODEPROGRAMA':([0,],[2,]),'$end':([1,18,],[0,-1,]),'LIBRERIA':([2,59,],[6,6,]),'VARIABLE':([2,8,9,10,11,12,39,40,41,46,57,60,61,64,69,70,73,],[14,14,14,14,14,14,-15,-16,-17,14,-14,14,-19,-12,-18,14,-13,]),'FUNCION':([2,8,9,10,11,12,39,40,41,46,57,60,61,64,69,70,73,],[15,15,15,15,15,15,-15,-16,-17,15,-14,15,-19,-12,-18,15,-13,]),'ID':([2,8,9,10,11,12,15,16,19,20,26,35,36,39,40,41,46,57,60,61,62,64,69,70,73,],[7,7,7,7,7,7,27,28,30,31,34,43,43,-15,-16,-17,7,-14,7,-19,43,-12,-18,7,-13,]),'PROCEDIMIENTO':([2,8,9,10,11,12,39,40,41,46,57,60,61,64,69,70,73,],[16,16,16,16,16,16,-15,-16,-17,16,-14,16,-19,-12,-18,16,-13,]),'IF':([2,8,9,10,11,12,39,40,41,46,57,60,61,64,69,70,73,],[17,17,17,17,17,17,-15,-16,-17,17,-14,17,-19,-12,-18,17,-13,]),'FINPROGRAMA':([2,3,4,5,8,9,10,11,12,13,21,22,23,24,25,39,40,41,57,60,61,64,66,67,69,73,],[-22,18,-2,-3,-22,-22,-22,-22,-22,-11,-6,-7,-8,-9,-10,-15,-16,-17,-14,-22,-19,-12,-4,-5,-18,-13,]),'PARENTESISA':([6,14,17,27,28,],[19,26,29,35,36,]),'IGUAL':([7,],[20,]),'END':([8,9,10,11,12,13,21,22,23,24,25,39,40,41,46,52,57,61,64,69,70,71,73,],[-22,-22,-22,-22,-22,-11,-6,-7,-8,-9,-10,-15,-16,-17,-22,58,-14,-19,-12,-18,-22,72,-13,]),'NUMBER':([20,],[32,]),'DECIMALNUMBER':([20,],[33,]),'PARENTESISC':([29,44,45,47,48,55,68,],[37,50,51,53,54,-21,-20,]),'OPERADORPUNTO':([30,],[38,]),'ENDOFLINE':([31,32,33,51,53,54,58,63,72,],[39,40,41,57,60,61,64,69,73,]),'VARTYPESEPARATOR':([34,43,50,],[42,49,56,]),'BEGIN':([37,65,],[46,70,]),'EXTENSION':([38,],[47,]),'TYPE':([42,49,56,],[48,55,63,]),'COMA':([53,55,],[59,62,]),'ELSE':([58,],[65,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'declaraciones':([2,],[3,]),'librerias':([2,59,],[4,66,]),'cuerpo':([2,8,9,10,11,12,46,60,70,],[5,21,22,23,24,25,52,67,71,]),'variable':([2,8,9,10,11,12,46,60,70,],[8,8,8,8,8,8,8,8,8,]),'funcion':([2,8,9,10,11,12,46,60,70,],[9,9,9,9,9,9,9,9,9,]),'asignacion':([2,8,9,10,11,12,46,60,70,],[10,10,10,10,10,10,10,10,10,]),'procedimiento':([2,8,9,10,11,12,46,60,70,],[11,11,11,11,11,11,11,11,11,]),'condicional':([2,8,9,10,11,12,46,60,70,],[12,12,12,12,12,12,12,12,12,]),'empty':([2,8,9,10,11,12,46,60,70,],[13,13,13,13,13,13,13,13,13,]),'argumentos':([35,36,62,],[44,45,68,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> INICIODEPROGRAMA declaraciones FINPROGRAMA','programa',3,'p_programa','yacc.py',6),
  ('declaraciones -> librerias','declaraciones',1,'p_declaraciones','yacc.py',9),
  ('declaraciones -> cuerpo','declaraciones',1,'p_declaraciones','yacc.py',10),
  ('librerias -> LIBRERIA PARENTESISA ID OPERADORPUNTO EXTENSION PARENTESISC COMA librerias','librerias',8,'p_librerias','yacc.py',13),
  ('librerias -> LIBRERIA PARENTESISA ID OPERADORPUNTO EXTENSION PARENTESISC ENDOFLINE cuerpo','librerias',8,'p_librerias','yacc.py',14),
  ('cuerpo -> variable cuerpo','cuerpo',2,'p_cuerpo','yacc.py',18),
  ('cuerpo -> funcion cuerpo','cuerpo',2,'p_cuerpo','yacc.py',19),
  ('cuerpo -> asignacion cuerpo','cuerpo',2,'p_cuerpo','yacc.py',20),
  ('cuerpo -> procedimiento cuerpo','cuerpo',2,'p_cuerpo','yacc.py',21),
  ('cuerpo -> condicional cuerpo','cuerpo',2,'p_cuerpo','yacc.py',22),
  ('cuerpo -> empty','cuerpo',1,'p_cuerpo','yacc.py',23),
  ('condicional -> IF PARENTESISA PARENTESISC BEGIN cuerpo END ENDOFLINE','condicional',7,'p_condicional','yacc.py',26),
  ('condicional -> IF PARENTESISA PARENTESISC BEGIN cuerpo END ELSE BEGIN cuerpo END ENDOFLINE','condicional',11,'p_condicional','yacc.py',27),
  ('procedimiento -> PROCEDIMIENTO ID PARENTESISA argumentos PARENTESISC ENDOFLINE','procedimiento',6,'p_procedimiento','yacc.py',30),
  ('asignacion -> ID IGUAL ID ENDOFLINE','asignacion',4,'p_asignacion','yacc.py',33),
  ('asignacion -> ID IGUAL NUMBER ENDOFLINE','asignacion',4,'p_asignacion','yacc.py',34),
  ('asignacion -> ID IGUAL DECIMALNUMBER ENDOFLINE','asignacion',4,'p_asignacion','yacc.py',35),
  ('funcion -> FUNCION ID PARENTESISA argumentos PARENTESISC VARTYPESEPARATOR TYPE ENDOFLINE','funcion',8,'p_funcion','yacc.py',39),
  ('variable -> VARIABLE PARENTESISA ID VARTYPESEPARATOR TYPE PARENTESISC ENDOFLINE','variable',7,'p_variable','yacc.py',42),
  ('argumentos -> ID VARTYPESEPARATOR TYPE COMA argumentos','argumentos',5,'p_argumentos','yacc.py',45),
  ('argumentos -> ID VARTYPESEPARATOR TYPE','argumentos',3,'p_argumentos','yacc.py',46),
  ('empty -> <empty>','empty',0,'p_empty','yacc.py',50),
]
